name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - "18.x"
          - "20.x"

    steps:
      - uses: actions/checkout@v3

      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: install deps
        run: yarn install --frozen-lockfile

      - name: run codegen
        run: yarn run codegen

      - name: run esbuild
        run: node esbuild.js
